# Generated by Django 4.1.4 on 2023-05-19 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AmazonShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('offer', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=50)),
                ('slug', models.SlugField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AffiliateSite',
        ),
    ]
