# Generated by Django 4.1.4 on 2023-05-19 08:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AmazonShop', '0002_affiliatemode_delete_affiliatesite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffiliateMode',
            new_name='AffiliateModeSite',
        ),
    ]
